const { PrismaClient } = require("@prisma/client");

const database = new PrismaClient();

const main = async () => {
  try {
    await database.category.createMany({
      data: [
        { name: "Software Development" },
        { name: "Web Development" },
        { name: "Mobile App Development" },
        { name: "Data Science" },
        { name: "Machine Learning" },
        { name: "Artificial Intelligence" },
        { name: "UI/UX Design" },
        { name: "Product Management" },
        { name: "Project Management" },
        { name: "Quality Assurance" },
        { name: "DevOps" },
        { name: "Cybersecurity" },
        { name: "Cloud Computing" },
        { name: "Database Administration" },
        { name: "Network Engineering" },
        { name: "Business Analysis" },
        { name: "Sales" },
        { name: "Marketing" },
        { name: "Customer Support" },
        { name: "Human Resources" },
        { name: "Finance" },
        { name: "Accounting" },
        { name: "Legal" },
        { name: "Education" },
        { name: "Healthcare" },
        { name: "Fitness" },
        { name: "Hospitality" },
        { name: "Travel" },
        { name: "Real Estate" },
        { name: "Construction" },
        { name: "Architecture" },
        { name: "Automotive" },
        { name: "Aviation" },
        { name: "Oil & Gas" },
        { name: "Mining" },
        { name: "Manufacturing" },
        { name: "Logistics" },
        { name: "Supply Chain" },
        { name: "Retail" },
        { name: "E-commerce" },
        { name: "Fashion" },
        { name: "Entertainment" },
        { name: "Sports" },
        { name: "Gaming" },
        { name: "Music" },
        { name: "Film" },
        { name: "Television" },
        { name: "Radio" },
        { name: "Journalism" },
        { name: "Publishing" },
        { name: "Public Relations" },
        { name: "Advertising" },
        { name: "Social Media" },
        { name: "Content Writing" },
        { name: "Copywriting" },
        { name: "Technical Writing" },
        { name: "Translation" },
        { name: "Proofreading" },
        { name: "Editing" },
        { name: "Transcription" },
        { name: "Voice Over" },
        { name: "Video Editing" },
        { name: "Animation" },
        { name: "Graphic Design" },
        { name: "Illustration" },
        { name: "Photography" },
        { name: "Videography" },
        { name: "Audio Production" },
        { name: "3D Modeling" },
        { name: "3D Rendering" },
        { name: "3D Animation" },
        { name: "3D Printing" },
        { name: "Virtual Reality" },
        { name: "Augmented Reality" },
        { name: "Game Development" },
        { name: "App Development" },
        { name: "Database Development" },
        { name: "Web Design" },
        { name: "Product Design" },
        { name: "Industrial Design" },
        { name: "Interior Design" },
        { name: "Fashion Design" },
        { name: "Jewelry Design" },
        { name: "Architectural Design" },
        { name: "Landscape Design" },
        { name: "Urban Design" },
        { name: "Garden Design" },
        { name: "Motion Graphics" },
        { name: "Visual Effects" },
        { name: "Music Production" },
        { name: "Sound Design" },
        { name: "Narration" },
        { name: "Audio Editing" },
        { name: "Audio Mixing" },
        { name: "Audio Mastering" },
        { name: "Audio Restoration" },
        { name: "Audio Post Production" },
        { name: "Audio Engineering" },
        { name: "Audio Recording" },
      ],
    });
    console.log("Success");
  } catch (error) {
    console.log(`Error on seeding the database categories: ${error}`);
  }
};

main();
